version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app

  app:
    build: 
      context: .
      # 開発時だけ有効にしたい
    volumes:
      - ./laravel:/var/www/html

  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql
