version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - app

  app:
    build: 
      context: .
      # 開発時だけ有効にしたい
    volumes:
      - ./laravel:/var/www/html
