version: "3.8"

services:
  cdk:
    container_name: "cdk"
    build:
      context: .
    init: true
    volumes:
      - ./:/home/node
      # awscliのcred用
      - ${HOME}/.aws/:/home/node/.aws/:ro

